import json
import os

def update_notebook():
    file_path = 'Mango_Quality_CNN_Training.ipynb'
    with open(file_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # Update cell 4 (ZIP Extract logic)
    for cell in nb['cells']:
        if cell['cell_type'] == 'code' and any('uploaded = files.upload()' in line for line in cell.get('source', [])):
            cell['source'] = [
                "import os\n",
                "from google.colab import files\n",
                "\n",
                "print('Click below to upload your mango dataset ZIP file:')\n",
                "uploaded = files.upload()\n",
                "\n",
                "for filename in uploaded.keys():\n",
                "    if filename.endswith('.zip'):\n",
                "        print(f'Extracting {filename} using native unzip...')\n",
                "        !unzip -q \"{filename}\" -d dataset/\n",
                "        print(f'Unzipped {filename} into dataset/')\n",
                "\n",
                "# Verify class folders\n",
                "CLASS_NAMES = ['Grade_A_Ripe', 'Grade_B_Unripe', 'Grade_C_Overripe', 'Non_Mango']\n",
                "for split in ['train', 'val']:\n",
                "    for c in CLASS_NAMES:\n",
                "        p = os.path.join('dataset', split, c)\n",
                "        if os.path.exists(p):\n",
                "            n = len([f for f in os.listdir(p) if f.lower().endswith(('.jpg','.jpeg','.png'))])\n",
                "            print(f'  dataset/{split}/{c}: {n} images')"
            ]

    # Update cell 10 (Training Loop with Distance Penalized Loss)
    for cell in nb['cells']:
        if cell['cell_type'] == 'code' and any('class FocalLoss' in line for line in cell.get('source', [])):
            cell['source'] = [
                "# ── Distance Penalized Focal Loss (Ordinal Regression) ────────────────────────\n",
                "class FocalLoss(nn.Module):\n",
                "    def __init__(self, gamma=2.0, reduction='none'):\n",
                "        super().__init__()\n",
                "        self.gamma = gamma\n",
                "        self.ce = nn.CrossEntropyLoss(reduction='none')\n",
                "        self.reduction = reduction\n",
                "        \n",
                "    def forward(self, inputs, targets):\n",
                "        ce_loss = self.ce(inputs, targets)\n",
                "        pt = torch.exp(-ce_loss)\n",
                "        focal_loss = (1 - pt) ** self.gamma * ce_loss\n",
                "        if self.reduction == 'mean': return focal_loss.mean()\n",
                "        return focal_loss\n",
                "\n",
                "class DistancePenalizedLoss(nn.Module):\n",
                "    def __init__(self, base_criterion):\n",
                "        super().__init__()\n",
                "        self.base_criterion = base_criterion\n",
                "\n",
                "    def forward(self, inputs, targets):\n",
                "        base_loss = self.base_criterion(inputs, targets)\n",
                "        _, preds = torch.max(inputs, 1)\n",
                "        \n",
                "        # Calculate distance penalty (Ignore class 3: Non_Mango)\n",
                "        valid_mask = (targets != 3) & (preds != 3)\n",
                "        distance = torch.abs(preds[valid_mask] - targets[valid_mask]).float()\n",
                "        \n",
                "        # Multiply base loss by distance (A->C is punished 2.0x, A->B is 1.5x)\n",
                "        penalty_weights = torch.ones_like(targets, dtype=torch.float, device=targets.device)\n",
                "        penalty_weights[valid_mask] = 1.0 + (distance * 0.5) \n",
                "        \n",
                "        return (base_loss * penalty_weights).mean()\n",
                "\n",
                "\n",
                "# ── Mixup Helpers ─────────────────────────────────────────────────────────────\n",
                "def mixup_data(x, y, alpha=0.4):\n",
                "    lam = np.random.beta(alpha, alpha)\n",
                "    idx = torch.randperm(x.size(0)).to(x.device)\n",
                "    return lam * x + (1 - lam) * x[idx], y, y[idx], lam\n",
                "\n",
                "def mixup_criterion(crit, pred, y_a, y_b, lam):\n",
                "    return lam * crit(pred, y_a) + (1 - lam) * crit(pred, y_b)\n",
                "\n",
                "\n",
                "# ── Training Configuration ────────────────────────────────────────────────────\n",
                "TOTAL_EPOCHS          = 40\n",
                "STAGE1_EPOCHS         = 5\n",
                "EARLY_STOPPING_PATIENCE = 10\n",
                "MODEL_SAVE_PATH       = 'mango_model.pth'\n",
                "\n",
                "model     = MangoEfficientNet(num_classes=len(CLASS_NAMES)).to(device)\n",
                "\n",
                "# Wrap FocalLoss with the new Distance Penalty\n",
                "base_criterion = FocalLoss(gamma=2.0, reduction='none')\n",
                "criterion = DistancePenalizedLoss(base_criterion)\n",
                "\n",
                "optimizer = optim.Adam(model.get_classifier_params(), lr=0.001, weight_decay=1e-4)\n",
                "scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=STAGE1_EPOCHS)\n",
                "\n",
                "history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}\n",
                "best_val_acc    = 0.0\n",
                "patience_counter = 0\n",
                "best_epoch      = 0\n",
                "\n",
                "print(f'Starting 2-Stage EfficientNet-B0 Training | {TOTAL_EPOCHS} max epochs | Early Stop patience={EARLY_STOPPING_PATIENCE}')\n",
                "print(f'Stage 1: Epochs 1-{STAGE1_EPOCHS} (frozen backbone, train head only)')\n",
                "print(f'Stage 2: Epochs {STAGE1_EPOCHS+1}+ (unfreeze upper blocks, differential LR, Mixup)\\n')\n",
                "\n",
                "import time\n",
                "start_time = time.time()\n",
                "\n",
                "for epoch in range(1, TOTAL_EPOCHS + 1):\n",
                "\n",
                "    # ── Stage 2 transition ───────────────────────────────────────────────────\n",
                "    if epoch == STAGE1_EPOCHS + 1:\n",
                "        print('\\nTRANSITIONING TO STAGE 2: Unfreezing upper EfficientNet-B0 backbone layers...')\n",
                "        model.unfreeze_backbone(unfreeze_from_block=5)\n",
                "        optimizer = optim.Adam([\n",
                "            {'params': model.get_backbone_params(), 'lr': 1e-5},\n",
                "            {'params': model.get_classifier_params(), 'lr': 1e-4}\n",
                "        ], weight_decay=1e-4)\n",
                "        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=TOTAL_EPOCHS - STAGE1_EPOCHS)\n",
                "        print('Differential LRs: Backbone=1e-5, Head=1e-4 | Mixup enabled\\n')\n",
                "\n",
                "    use_mixup = (epoch > STAGE1_EPOCHS)\n",
                "\n",
                "    # ── Training loop ────────────────────────────────────────────────────────\n",
                "    model.train()\n",
                "    running_loss, correct, total = 0.0, 0, 0\n",
                "\n",
                "    for imgs, lbls in train_loader:\n",
                "        imgs, lbls = imgs.to(device), lbls.to(device)\n",
                "        optimizer.zero_grad()\n",
                "\n",
                "        if use_mixup and np.random.random() < 0.5:\n",
                "            mixed_imgs, y_a, y_b, lam = mixup_data(imgs, lbls)\n",
                "            outs = model(mixed_imgs)\n",
                "            loss = mixup_criterion(criterion, outs, y_a, y_b, lam)\n",
                "            _, preds = torch.max(outs, 1)\n",
                "            correct += (lam * (preds == y_a).float() + (1 - lam) * (preds == y_b).float()).sum().item()\n",
                "        else:\n",
                "            outs = model(imgs)\n",
                "            loss = criterion(outs, lbls)\n",
                "            _, preds = torch.max(outs, 1)\n",
                "            correct += (preds == lbls).sum().item()\n",
                "\n",
                "        loss.backward()\n",
                "        optimizer.step()\n",
                "        running_loss += loss.item() * imgs.size(0)\n",
                "        total += lbls.size(0)\n",
                "\n",
                "    scheduler.step()\n",
                "    train_loss = running_loss / total\n",
                "    train_acc  = (correct / total) * 100\n",
                "\n",
                "    # ── Validation loop ──────────────────────────────────────────────────────\n",
                "    model.eval()\n",
                "    val_loss_sum, val_correct, val_total = 0.0, 0, 0\n",
                "    with torch.no_grad():\n",
                "        for imgs, lbls in val_loader:\n",
                "            imgs, lbls = imgs.to(device), lbls.to(device)\n",
                "            outs = model(imgs)\n",
                "            val_loss_sum += criterion(outs, lbls).item() * imgs.size(0)\n",
                "            _, preds = torch.max(outs, 1)\n",
                "            val_correct += (preds == lbls).sum().item()\n",
                "            val_total   += lbls.size(0)\n",
                "\n",
                "    val_loss = val_loss_sum / max(1, val_total)\n",
                "    val_acc  = (val_correct / max(1, val_total)) * 100\n",
                "\n",
                "    history['train_loss'].append(train_loss)\n",
                "    history['train_acc'].append(train_acc)\n",
                "    history['val_loss'].append(val_loss)\n",
                "    history['val_acc'].append(val_acc)\n",
                "\n",
                "    stage = 'Stage 1' if epoch <= STAGE1_EPOCHS else 'Stage 2'\n",
                "    improved_marker = '  <-- BEST' if val_acc > best_val_acc else ''\n",
                "    print(f'[{stage}] Epoch [{epoch:02d}/{TOTAL_EPOCHS}] | Train Loss:{train_loss:.4f} Acc:{train_acc:.2f}% | Val Loss:{val_loss:.4f} Acc:{val_acc:.2f}%{improved_marker}')\n",
                "\n",
                "    # ── Early Stopping & Best Model Save ────────────────────────────────────\n",
                "    if val_acc > best_val_acc:\n",
                "        best_val_acc = val_acc\n",
                "        best_epoch   = epoch\n",
                "        patience_counter = 0\n",
                "        torch.save(model.state_dict(), MODEL_SAVE_PATH)\n",
                "        print(f'   [SAVED] Best model saved! Val Acc: {best_val_acc:.2f}% at epoch {best_epoch}')\n",
                "    else:\n",
                "        patience_counter += 1\n",
                "        if patience_counter >= EARLY_STOPPING_PATIENCE:\n",
                "            print(f'\\n[EARLY STOP] No improvement for {EARLY_STOPPING_PATIENCE} epochs.')\n",
                "            print(f'Best Val Acc: {best_val_acc:.2f}% at epoch {best_epoch}')\n",
                "            break\n",
                "\n",
                "elapsed = time.time() - start_time\n",
                "print(f'\\nTraining complete in {elapsed/60:.1f} minutes.')\n",
                "print(f'Best Validation Accuracy: {best_val_acc:.2f}% at Epoch {best_epoch}')"
            ]

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1)

if __name__ == '__main__':
    update_notebook()
